### PR TITLE
Fix useHookstate store switchover

### LINKED ISSUE #364: Prevent HOOKSTATE-111 exception being raised during Vite and NextJS HMR
Upvote this if you are interested in this feature.

### PR DESCRIPTION
**Pull request by the-reality-engineer**
This PR adds support for store switchovers to useHookstate() for global and nested state. Local state behavior remains unchanged. Additionally, setting state after unmount no longer throws an error, which is more in line w/ how React's built-in useState hook works.  

TLDR; Eliminated HOOKSTATE-111 and HOOKSTATE-106 exceptions. 

closes #364

### CODE REVIEW

File: core/src/__tests__/Complex.tsx [hunk 1]
```diff
@@ -199,3 +199,78 @@ test('complex: should auto save latest state for unmounted', async () => {
...
+    act(() => {
+        result.current.set(p => p + 1);
+    });
+
+    expect(result.current.get()).toBe(1);
+    expect(renderTimes).toBe(2);
+
+    rerender({ source: newStore });
+
+    expect(renderTimes).toBe(3);
```
Comment (avkonst) [inline core/src/__tests__/Complex.tsx:251]: could you please extend the tests to make sure we can do state set action after the store is reinitialized? same for other tests you put.

File: core/src/index.ts [hunk 2]
```diff
@@ -1056,7 +1066,8 @@ class Store implements Subscribable {
     set(path: Path, value: StateValueAtPath): SetActionDescriptor {
         if (this.edition < 0) {
             // TODO convert to console log
```
Comment (avkonst) [inline core/src/index.ts:1068]: maybe remove TODO comment? and update web docs for this error code?

**Comment by avkonst** [comment]
Hi @speigg ... could you please let me know if you are planning to address my comments?

**Comment by speigg** [comment]
Hi @avkonst I'd be happy to address your comments as soon as I have finished taking care of other things on my plate. Might take me another week to get to this.

File: core/src/__tests__/Complex.tsx (hunk 1 above)
Comment (speigg) [reply core/src/__tests__/Complex.tsx:258]: done

File: core/src/index.ts (hunk 2 above)
Comment (speigg) [reply core/src/index.ts]: I removed this block entirely, as the warnings were excessive in our usage, and there are legitimate reasons for updating global state while a component unmounts (updating hooked global state on unmount).

**Comment by speigg** [comment]
Should be good now. Apologies for the long delay.

**Comment by speigg** [comment]
As I mentioned in a comment above, I removed the HOOKSTATE-106 warning entirely, as the warnings were excessive in our usage, and there are legitimate reasons for updating global state while a component unmounts (updating hooked global state on unmount).

**Comment by speigg** [comment]
@avkonst any chance you can look at this soon? Thanks!

**Comment by HexaField** [comment]
Thank you!!!
